### ISSUE TITLE
yarn run lib is not working

### ISSUE THREAD

**Issue by shabanraza** [lokhmakov/create-react-app-npm#1]
It showing below error

yarn run v0.22.0
$ babel src/node_modules --out-dir lib --copy-files 
sh: 1: babel: not found
error Command failed with exit code 127.

**Comment by lokhmakov** [comment]
```
sudo npm -g install babel
```

**Comment by lokhmakov** [comment]
And I recommend to look on configuration without eject: https://github.com/lokhmakov/create-react-app-stories
